apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
   annotations:
     github.com/project-slug: backstage/backstage
     backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  # Your API definition goes here, or a reference to a file.
    # For example, if using OpenAPI:
  definition:
    $text: 'https://github.com/leonardolopardo/backstage/blob/main/swagger.yaml'
